In [1]:
import numpy as np

In [2]:
my_lst=[1,2,3,4,5]
arr1=np.array(my_lst)
arr1

array([1, 2, 3, 4, 5])

In [3]:
type(arr1)

numpy.ndarray

In [5]:
arr1.shape

(5,)

In [4]:
my_lst=[1,2,3,4,5]
arr2=np.array([my_lst])
arr2

array([[1, 2, 3, 4, 5]])

In [6]:
arr2.shape

(1, 5)

In [7]:
l1=[1,2,3,4,5]
l2=[3,4,5,2,4]
l3=[6,7,4,6,7]
arr3=np.array([l1,l2,l3])
arr3

array([[1, 2, 3, 4, 5],
       [3, 4, 5, 2, 4],
       [6, 7, 4, 6, 7]])

In [8]:
arr3.shape

(3, 5)

In [10]:
arr4=arr3.reshape(5,3)
arr4

array([[1, 2, 3],
       [4, 5, 3],
       [4, 5, 2],
       [4, 6, 7],
       [4, 6, 7]])

In [11]:
arr3*2

array([[ 2,  4,  6,  8, 10],
       [ 6,  8, 10,  4,  8],
       [12, 14,  8, 12, 14]])